### ISSUE TITLE
Unable to remove foreground color in windows 

### ISSUE THREAD

**Issue by rachidlaborantin** [DJ-Raven/tabbed-pane-material#1]
Hi
Good work for your project, I appreciate it 
I've use it in my app but I'm not able to remove the foreground color of the title of the selected tab. 
(See it in the picture) 
![IMG_20220313_123943](https://user-images.githubusercontent.com/81116574/158057741-6b881746-1b2a-4fb5-a9f4-2b334be53b78.png)

Hope you can find it and fix it

**Comment by DJ-Raven** [comment]
Background color fixed
